feature/48/add-descriptions (#48)
Ceredira/CerediraTess pull request #65
Opened 2022-06-16 11:51 UTC by RadostDudhi

2022-07-02 19:28 UTC, unixshaman requested changes

2022-07-02 19:28 UTC, unixshaman commented on ceredira_tess/forms.py
> +        scripts='Ссылка на реальный файл лежащий на сервере в каталоге scripts',
Список скриптов, доступных для выполнения на агенте

2022-07-02 19:28 UTC, unixshaman commented on ceredira_tess/forms.py
> +        roles='Объединение пользователей, которые получают идентичные права на доступ к Агентам системы'
Список ролей, к которым принадлежит агент.

2022-07-02 19:28 UTC, unixshaman commented on ceredira_tess/forms.py
> +        osname='ОС агента'
Операционная система агента

2022-07-02 19:28 UTC, unixshaman commented on ceredira_tess/forms.py
> +        operationsystemtype='ОС агента',
Операционная система агента

2022-07-02 19:28 UTC, unixshaman commented on ceredira_tess/forms.py
> +        description='Описание роли, можно описать какие права доступа  имеет данная роль, принадлежность к проекту',
Описание роли. Можно описать какие права доступа  имеет данная роль, принадлежность к проекту.

2022-07-02 19:28 UTC, unixshaman commented on ceredira_tess/forms.py
> +        users='Пользователь - это аккаунт, к которому администратор присваивает роль'
Пользователи - это аккаунты системы, которых администратор добавляет к данной роли для возможности доступа к выполнению скриптов на агентах, добавленные в эту роль.

2022-07-02 19:28 UTC, unixshaman commented on ceredira_tess/forms.py
> +        agents='Агенты на которых выполняется обработка скрипта'
Агенты на которых выполняются скрипты

2022-07-04 14:43 UTC, RadostDudhi reviewed
changed some description according to the comment

2023-12-17 19:26 UTC, merged